trigger:
  - main

pool:
  vmImage: 'ubuntu-latest'

variables:
  azureServiceConnection: 'MyAzureServiceConnection' 
  resourceGroupName: 'rg-terraform-backend' 
  storageAccountName: 'stpoc17backend'       
  containerName: 'tfstate'
  tfstateKey: 'poc17.tfstate'

stages:
- stage: Build
  displayName: 'Build and Package Code'
  jobs:
  - job: Pack
    steps:
    - task: ArchiveFiles@2
      inputs:
        rootFolderOrFile: 'src'
        includeRootFolder: false
        archiveType: 'zip'
        archiveFile: '$(Build.ArtifactStagingDirectory)/app.zip'
        replaceExistingArchive: true

    - task: PublishBuildArtifacts@1
      inputs:
        PathtoPublish: '$(Build.ArtifactStagingDirectory)/app.zip'
        ArtifactName: 'drop-app'
        publishLocation: 'Container'

    - task: PublishBuildArtifacts@1
      inputs:
        PathtoPublish: 'terraform'
        ArtifactName: 'drop-terraform'
        publishLocation: 'Container'

- stage: DeployInfrastructure
  displayName: 'Provision Infrastructure'
  dependsOn: Build
  jobs:
  - job: Terraform
    steps:
    - task: DownloadBuildArtifacts@0
      inputs:
        buildType: 'current'
        downloadType: 'single'
        artifactName: 'drop-terraform'
        downloadPath: '$(System.ArtifactsDirectory)'

    - task: AzureCLI@2
      displayName: 'Install Terraform and Apply'
      inputs:
        azureSubscription: '$(azureServiceConnection)'
        scriptType: 'bash'
        scriptLocation: 'inlineScript'
        addSpnToEnvironment: true
        workingDirectory: '$(System.ArtifactsDirectory)/drop-terraform'
        inlineScript: |
          echo "===> Downloading Independent Terraform Binary to Temporary Location..."
          wget -q -O /tmp/
